---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  annotations:
    configmap.fabric8.io/update-on-change: "jenkins"
    fabric8.io/target-platform: "kubernetes"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: "fabric8/jenkins-openshift:${jenkins-openshift.version}"
        imagePullPolicy: "IfNotPresent"
        name: "jenkins"
        readinessProbe:
          timeoutSeconds: 10
          initialDelaySeconds: 10
          httpGet:
            path: "/login"
            port: 8080
        livenessProbe:
          timeoutSeconds: 10
          initialDelaySeconds: 420
          failureThreshold: 30
          httpGet:
            path: "/login"
            port: 8080
        ports:
        - containerPort: 50000
          name: "slave"
        - containerPort: 8080
          name: "http"
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: KUBERNETES_MASTER
          value: "https://kubernetes.default:443"
        - name: MAX_METASPACE_SIZE
          value: 200m
        - name: JENKINS_OPTS
          value: "-Dgroovy.use.classvalue=true"
        - name: JAVA_HOME
          value: "/etc/alternatives/java_sdk"
        - name: MAVEN_OPTS
          value: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
        - name: TEST_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: admin-user
              key: test.admin.password
        resources:
            limits:
              memory: 1Gi
              cpu: 0.5
            requests:
              cpu: "0"
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: jenkins-home
          readOnly: false
        - name: jenkins-config
          mountPath: /opt/openshift/configuration/
        - name: admin-user
          mountPath: /var/lib/jenkins/init.groovy.d/
      serviceAccountName: "jenkins"
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-home
      - name: jenkins-config
        configMap:
          name: jenkins
      - name: admin-user
        configMap:
          name: admin-user
