---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg"
  labels:
    provider: "fabric8"
    app: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "content-repository"
spec:
  replicas: 1
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 7200
  template:
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/caddy-server:${caddy-server.version}"
        imagePullPolicy: "IfNotPresent"
        name: "content-repository"
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 9180
          name: "prometheus"
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: "0"
        volumeMounts:
        - mountPath: "/var/www/html"
          name: "content"
          readOnly: false
      - env:
        - name: "OSIO_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "OSIO_ACL_SERVER"
          valueFrom:
            configMapKeyRef:
              key: "osio-acl-server"
              name: "content-repository"
        image: "registry.devshift.net/perf/oso-webapi-guard"
        name: oso-webapi-guard
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 8001
            name: "pcp-webguard"
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: content-repository
